### ISSUE TITLE
nwg-hello works with labwc too

### ISSUE THREAD

**Issue by 01micko** [nwg-piotr/nwg-hello#16]
Hello @nwg-piotr 

I've been working on porting [BunsenLabs](https://www.bunsenlabs.org), an openbox/debian based distro to `labwc` - which you may know is an `openbox` 'clone' (for want of a better term) for wlroots/wayland.

It works quite well as a replacement for `sway`/`hyperland` in the `greetd` configs to start `nwg-hello`.

I wrote about it [on bunsen forums](https://forums.bunsenlabs.org/viewtopic.php?pid=135089#p135089) (includes configs and diffs) however the info doesn't pertain to the latest version but `v0.1.10`, the latest in the debian trixie repos as of now.

I wonder if you can add the info to the docs to help folk like me who had to use a bit of trial and error to get things working smoothly.

Thanks for reading.

**Comment by nwg-piotr** [comment]
Sure, but we would have to reconcile a few inconsistencies.

> Apparently this can be cpoied to /etc/greetd/greetd.toml so it survives an upgrade.

The alternative config file name is `greetd.conf`, not `greetd.toml`.

Also, if possible, I'd prefer `/etc/nwg-hello/` as the compositor config file location, as we already have hyprland and sway config there.

**Comment by 01micko** [comment]
Thanks for consideration.

I'll make the necessary adjustments to my current system and post new configs in this thread.

**Comment by nwg-piotr** [comment]
Excellent, thanks!

**Comment by 01micko** [comment]
Did the migration, now to test. If successful do you want me to issue a PR?

**Comment by 01micko** [comment]
Interesting. `greetd.conf` doesn't work here. Maybe a debian quirk?

Anyway the migration _did_ work with `greetd.toml`, oh and screenshot saved in `_greetd`'s home ;)

### list of /etc/greetd

```
mick@dellhome:~$ sudo ls -la /etc/greetd/
[sudo] password for mick:
total 152
drwxr-xr-x   4 _greetd _greetd   4096 Jun  9 10:05 .
drwxr-xr-x 121 root    root     12288 Jun  9 10:01 ..
drwx------   3 _greetd _greetd   4096 Jun  7 22:35 .cache
drwx------   3 _greetd _greetd   4096 Jun  7 20:08 .config
-rw-rw-r--   1 _greetd _greetd 119123 Jun  9 10:05 20240609_10h05m51s_grim.png
-rw-r--r--   1 _greetd _greetd    669 Jun  7 22:33 config.toml.bak
-rw-r--r--   1 _greetd _greetd    672 Jun  9 09:46 greetd.toml
```

### list of /etc/nwg-hello

```
mick@dellhome:~$ sudo ls -la /etc/nwg-hello/
total 92
drwxr-xr-x   3 root root  4096 Jun  9 09:40 .
drwxr-xr-x 121 root root 12288 Jun  9 10:01 ..
-rw-r--r--   1 root root   192 Apr 28 21:12 README
-rw-r--r--   1 root root   175 Apr 28 21:12 hyprland.conf
drwxr-xr-x   2 root root  4096 Jun  9 09:40 lab-config
-rw-r--r--   1 root root 41190 Jun  8 10:05 labwall0-1920x1080.jpg
-rw-r--r--   1 root root   897 Apr 28 21:12 nwg-hello-default.css
-rw-r--r--   1 root root   496 Apr 28 21:12 nwg-hello-default.json
-rw-r--r--   1 root root   906 Jun  8 10:12 nwg-hello.css
-rw-r--r--   1 root root   497 Jun  8 11:10 nwg-hello.json
-rw-r--r--   1 root root   213 Apr 28 21:12 sway-config
```

**Comment by 01micko** [comment]
### configs

#### /etc/greetd/greetd.toml

```toml
[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 7

# The default session, also known as the greeter.
[default_session]

command = "labwc --config-dir /etc/nwg-hello/lab-config"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greetd"
```

#### /etc/nwg-hello/lab-config/autostart

```sh
# start nwg-hello - full paths aren't required, but saves lookup time
exec /usr/bin/nwg-hello; /usr/bin/labwc --exit
```

#### /etc/nwg-hello/lab-config/rc.xml (optional)
- only if you want a screenshot (using `PrtScr` key) of `nwg-hello` saved to /etc/greetd/

```xml
 <?xml version="1.0" ?>
<labwc_config>

  <keyboard>
    <default />
    <keybind key="Print"><action name="Execute" command="grim" /></keybind>
  </keyboard>

</labwc_config>
```
