### ISSUE TITLE
nwg-hello focus on start

### ISSUE THREAD

**Issue by yawor** [nwg-piotr/nwg-hello#20]
Hi,

I have a problem with nwg-hello window grabbing focus. I need to move the mouse cursor for the window to grab the focus. Without that it's not possible to do anything with just a keyboard.

I'm using arch linux and sway and I've set nwg-hello in greetd exactly how it's described in the README. I'm also using default nwg-hello configuration. This happens on both a desktop PC with AMD GPU and a laptop with Intel GPU.

**Comment by yawor** [comment]
I've tried to force the focus using swaymsg with focus command, but the problem is the nwg-hello is not even visible when I execute `swaymsg -t get_tree`, so I'm not able to select the window using criteria.
For now I've found a workaround. I've added
```
exec "sleep 2; swaymsg seat - cursor release button1"
```
to `/etc/nwg-hello/sway-config`.
This is somehow able to focus the nwg-hello window, but it depends on the 2 second delay. For my PC this works properly, but it may require longer delay for slower hardware, as the command needs to be called after the nwg-hello is displayed. Maybe there's some way to detect when the nwg-hello is displayed and then run the command, instead of depending on specific delay.

**Comment by nwg-piotr** [comment]
The window opens on gtk-layer-shell, so it's invisible to the compositor. 

I like your idea. Will try to trigger it from the application level.

**Comment by so1ar** [comment]
> Works well if you use Hyprland as the compositor.

Hi, I found out the similar issue, except I'm using Hyprland as the compositor. Don't know if it is because the recent 0.43.0 release of Hyprland.

**Comment by nwg-piotr** [comment]
@so1ar Doesn't happen on my side. May I see your `/etc/greetd/greetd.conf`?

**Comment by so1ar** [comment]
@nwg-piotr My greetd config file is pretty much default:
```toml
[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
#command = "agreety --cmd /bin/sh"
command = "Hyprland -c /etc/nwg-hello/hyprland.conf"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
```

I downgraded Hyprland to version 0.42.0, the problem went away. I think it's something to do with the Hyprland 0.43.0 release.
